### ISSUE TITLE
Issue with default command?

### ISSUE THREAD

**Issue by caussourd** [docker-library/haproxy#1]
I'm running Docker 1.5 and haproxy:1.5

As a user pointed out on the [Docker hub page] (https://registry.hub.docker.com/_/haproxy/), I had to override the command with `haproxy -db -f /usr/local/etc/haproxy/haproxy.cfg` to run the container. 

With the default command (`CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]`), the container exits with no logs. 

Apparently, the `-db` option allows haproxy to run in foreground: http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#3.1

**Comment by tianon** [comment]
I'm +1 on fixing this, but I'm not sure `-db` is recommended for generic use:
> -db
> Disables background mode (stays in foreground, useful for debugging). For debugging, the '-db' option is very useful as it temporarily disables daemon mode *and multi-process mode*. The service can then be stopped by simply pressing Ctrl-C, without having to edit the config nor run full debug.

Isn't running haproxy single-threaded a bit of a problem?

**Comment by calh** [comment]
Check your haproxy.cfg for `daemon` listed in the global mode.  I was stumped on this as well until that jumped out at me in my config file.  (I had just copied a config from another test haproxy instance I use on my workstation)

When I removed `daemon`, the docker image ran correctly in the foreground with the default image command.

**Comment by caussourd** [comment]
That's it. Well spotted. Thanks @calh

**Comment by dbu** [comment]
hah! tried to improve the documentation: https://github.com/docker-library/docs/pull/248
