### ISSUE TITLE
Can't Access Environment Vars

### ISSUE THREAD

**Issue by michaeljs1990** [docker-library/haproxy#10]
I am unable to access environment variables when using the 1.5.x version of ha proxy. I have tried with env and $ and both do not work. having trouble looking into the issue since I can't access /proc/??/environ inside the docker container.

**Comment by yosifkit** [comment]
How are you accessing the env?  Is this inside the config file?  The env command seems to return all the expected values. :confused: 
```console
$ docker run -it --rm haproxy env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=85d49e8a739f
TERM=xterm
HAPROXY_MAJOR=1.5
HAPROXY_VERSION=1.5.14
HAPROXY_MD5=ad9d7262b96ba85a0f8c6acc6cb9edde
HOME=/root
```

**Comment by michaeljs1990** [comment]
When I run..

```
docker exec -it haproxy env
```

I have  a different set of environment variables returned then when i enter the container though /bin/bash and run env. What cases this? I am setting environment variables in my docker-compose file that i would like to access in the cfg file. Is this possible?

**Comment by michaeljs1990** [comment]
I am guessing this is just me not understanding docker properly. I have only been playing with it for a week now.

**Comment by michaeljs1990** [comment]
So I rebuilt the container and ran the same command as above `docker exec -it haproxy env` and it outputs all the proper environment variables however I am not able to access them in the cfg file still. Since haproxy is run from the command line instead of as a service I believe it should have access to all of the same environment variables that i have when running that command.

**Comment by yosifkit** [comment]
Whatever process is started by docker (the `CMD`) uses the environment set up by docker (which includes any `environment` list when run through `docker-compose`).  Maybe try `docker-compose run my-haproxy bash` and see that `env` shows the configured values from the compose yaml.  I think that there are limited places that you can reference env vars in the haproxy config, but I am not that familiar with it.

**Comment by michaeljs1990** [comment]
I just tried that docker-compose command and ran env when logged in. It has all the environment variables I am looking for set however It seems to still not be setting it right in my config. This is my config file if it helps at all.

```
global
  stats socket /tmp/haproxy.sock mode 600 level admin

defaults
  mode http
  stats enable
  stats uri /haproxy_stats
  stats realm HAProxy\ Statistics
  stats auth username:password
  stats refresh 5s

frontend http-proxy
  bind *:80
  acl ser hdr(host) -i ${URL_1}
  acl pay hdr(host) -i ${URL_2}
  use_backend server if ser
  use_backend payments if pay
  default_backend server

backend server
   balance roundrobin
   server ser1 server:80 check

backend payments
  balance roundrobin
  server pay1 payments:3000 check
```

**Comment by michaeljs1990** [comment]
the one place i found working environment variables with haproxy was in this repo https://github.com/evanp/haproxy/blob/master/haproxy-start.sh

**Comment by yosifkit** [comment]
Haproxy does have access to the docker set environment variables; I'm just not sure that it will interpret them for any value in the config file.  Does the exact config work outside of docker?

**Comment by michaeljs1990** [comment]
I have seen posts of people using environment variables with haproxy. Although i just tested it locally on a non docker machine and it does not work as well. Can't find anything in the docs about where you can or can't use them as well.. I'm at a loss. Guess it's back to writing sed scripts to config stuff.

**Comment by michaeljs1990** [comment]
http://serverfault.com/questions/693753/using-haproxy-environmental-variables-in-haproxy-cfg-not-working here is the post where someone was using it and apparently got it working eventually. But of course they don't bother to say how.

**Comment by normanjoyner** [comment]
I got this working locally with the following:

__Dockerfile__
```dockerfile
FROM haproxy:1.5.14
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
```

__haproxy.cfg__
```
global
  stats socket /tmp/haproxy.sock mode 600 level admin

defaults
  mode http

frontend http-proxy
  bind *:${PORT}
```

__Docker run invocation__
`docker run -d -e PORT=1234 [image_id] haproxy -db -f /usr/local/etc/haproxy/haproxy.cfg`

**Comment by michaeljs1990** [comment]
The -db seemed to be the trick! Thanks a ton norman.

**Comment by michaeljs1990** [comment]
Spoke a little to soon. This works for bind it seems but when i use it for setting the dns in ACL it does not... although it passes the config check. Have been looking all over to find a list of places environment variables are supported but the haproxy documentation although verbos is somewhat useless.

**Comment by michaeljs1990** [comment]
This is an haproxy issue although the base image may want to be update to use the -db flag.

**Comment by RedbackThomson** [comment]
For historical purposes:
@michaeljs1990 needed to put his environment variables within double quotations marks in order for them to be interpreted as such by haproxy, rather than string literals.

Therefore his config file should have been:

```cfg
global
  stats socket /tmp/haproxy.sock mode 600 level admin

defaults
  mode http

frontend http-proxy
  bind "*:${PORT}"

**Comment by dlgoodchild** [comment]
I can confirm that I too had this issue and was simply resolved by enclosing the values using those environment variables with double quotes.
In my particular case I had:

```
frontend http-in
    bind *:80
    bind *:443 ssl crt ${SSL_PATH}${SSL_CERT}
```
...and to get this working I had to change to:

```
frontend http-in
    bind *:80
    bind *:443 ssl crt "${SSL_PATH}${SSL_CERT}"
```

**Comment by devopsw18** [comment]
Hi @dlgoodchild,

I am using HAProxy version 2.8.5-1ppa1 and my backend app are running reactjs app but clients keep getting  Invalid environment variables: 
These variables are defined in the env_file for the reactjs and its 100% present but haproxy doest serve it some how. If I run the app not through haproxy then no problem.

Any idea what can be the issue or what I must set on the haproxy confi

**Comment by dlgoodchild** [comment]
@devopsw18 your issue doesn't look like it has anything to do with haproxy, your describing an issue with using environment variables in your react application. Haproxy doesn't pass environment variables to whatever it proxies to. You should go back to investigating your issue from within the scope of your react project.
Good luck.
