### ISSUE TITLE
Haproxy with OpenSSL 1.1.1c ignores specified DH params

### ISSUE THREAD

**Issue by profbug** [docker-library/haproxy#100]
This works in 1.9.7 but was broken in 1.9.8, seemingly from the underlying update to OpenSSL.

To reproduce just set `ssl-dh-param-file` and point it to a dh param file (e.g https://ssl-config.mozilla.org/ffdhe2048.txt)

Expected/1.9.7 result (using [the latest TestSSL](https://github.com/drwetter/testssl.sh/releases/tag/3.0rc4))
> common prime with 2048 bits detected: RFC7919/ffdhe2048 (2048 bits)

Actual/1.9.8 result:
> common prime with 2048 bits detected: RFC5114/2048-bit DSA group with 224-bit prime order subgroup (2048 bits)

I also tried appending the DH params to the bottom of the CRT pem files with the same result.

**Comment by wglambert** [comment]
Right, `haproxy:1.9.8` is on Debian Buster https://github.com/docker-library/haproxy/commit/f3ff4cd3d32d9eceda4b33183a91d8d276bc08d5#diff-51c95e8cd4f39fd0a0428238d2574e74

Stretch uses openssl 1.1.0 https://packages.debian.org/stretch/openssl
Buster is on 1.1.1 https://packages.debian.org/buster/openssl

**Comment by wglambert** [comment]
Have you tried testing this outside of a container environment?
If you could get a minimal reproducer that would help quite a bit for probing the issue

**Comment by tianon** [comment]
I'm not sure what's actionable here for us?  Is there something we should fix in the image? (If so, do we have a pointer to some specific HAproxy documentation to help guide us in making the fix appropriately?)

**Comment by profbug** [comment]
Resolved upstream in https://github.com/haproxy/haproxy/issues/324
