### ISSUE TITLE
[RFE] Accept all configuration files from a directory

### ISSUE THREAD

**Issue by morenod** [docker-library/haproxy#105]
With current CMD line, all configuration needs to be added to the same file `/usr/local/etc/haproxy/haproxy.cfg`

Haproxy allows to use `-f <<folder>>` to include all files from that folder, adding a parameter on the `CMD` line will allow user to include a folder with all the configuration files

**Comment by yosifkit** [comment]
The [entrypoint script](https://github.com/docker-library/haproxy/blob/9024f3f2012caaf06774bdddc6c9ff485205c6ca/2.1/docker-entrypoint.sh#L5-L7) can make this sort of customization simple (so you don't need an extra `haproxy`):

```
$ docker run ... haproxy:2.1 -f /path/to/my/dir/
```

You'll notice that `/usr/local/etc/haproxy/haproxy.cfg` doesn't even exist in the image, so the default `CMD` is really just an example of how you could use it.

> Since no two users of HAProxy are likely to configure it exactly alike, this image does not come with any default configuration.
>
> \- from docs on [Docker Hub page](https://github.com/docker-library/docs/tree/657531b13966f6839277e216dfd8afbb0f44d867/haproxy#how-to-use-this-image)
