### ISSUE TITLE
how to forward request and error logs to docker log collector

### ISSUE THREAD

**Issue by 695097494** [docker-library/haproxy#106]
I want to see haproxy's request and error logs in the docker log collector after I start haproxy in Docker; how can I do this?

**Comment by wglambert** [comment]
HAproxy doesn't support logging to file descriptors (stdout/err) until version 1.9.0
There was a lengthy discussion on haproxy and logging here https://github.com/docker-library/haproxy/pull/39

One of the recommended workarounds was to mount the hosts `/dev/log` as the container's log file https://github.com/docker-library/haproxy/pull/39#issuecomment-338069656

https://github.com/docker-library/haproxy/pull/39#issuecomment-448814374
>Closing as `1.9.0` added support for "logging to existing file descriptors" (aka stdout) and is now GA. It will be available on the Docker Hub shortly.

**Comment by wglambert** [comment]
https://www.haproxy.com/blog/haproxy-1-9-has-arrived/
>When using HAProxy 1.9, you will now be able to take advantage of three new ways to send logs: send them to a file descriptor, to stdout, or to stderr. These new methods can be added using the standard `log` statement. . . .

**Comment by 695097494** [comment]
> https://www.haproxy.com/blog/haproxy-1-9-has-arrived/
> 
> > 使用HAProxy 1.9时，您现在可以利用三种新方式发送日志：将它们发送到文件描述符，stdout或stderr。可以使用标准`log`语句添加这些新方法。。。。

thank you for your help
