### ISSUE TITLE
haproxy 2.0.14+ alpine releases missing ca-certificates package

### ISSUE THREAD

**Issue by dekimsey** [docker-library/haproxy#117]
It appears that as of the 2.0.14-alpine release the system `ca-certificates` package is no longer being included. The Dockerfile lists the bundle as a build-time dependency and is getting removed after install. I'm not sure if this change was intentional or an oversight due to the alpine upgrade. But if I get to vote, I would like to see a system bundle installed by default. :) I'm not sure if the debian ones have an installed cert bundle.

We noticed this when our refreshed containers could no longer read the system packaged CA bundle.

Thank you!

**Comment by wglambert** [comment]
`ca-certificates` in the Alpine variant hasn't changed from being in the `.build-deps` virtual package (and being removed)

And I also don't see anything from 2.0.13 -> 2.0.14 that was changed https://github.com/docker-library/repo-info/commit/a014f75ab83f4bd4010455a332cf19086a4e3aab#diff-d6b328bd0a7ecc9fb29322c87f35b1b6

**Comment by dekimsey** [comment]
(I'm not on my workstation, so I'm cribbing from memory, I apologize this reply will not be fully fleshed out or not be fully correct)

Here's the test I did earlier today:
```
$ docker run --rm -it haproxy:2.0.13-alpine stat /etc/ssl/cert.pem
... file exists
$ docker run --rm -it haproxy:2.0.14-alpine stat /etc/ssl/cert.pem
... no such file
```

**Comment by tianon** [comment]
Definitely looks like a bug in Alpine:

```console
$ docker pull alpine:3.12
3.12: Pulling from library/alpine
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Image is up to date for alpine:3.12
docker.io/library/alpine:3.12

$ docker run -it --rm alpine:3.12
/ # stat -L /etc/ssl/cert.pem
  File: /etc/ssl/cert.pem
  Size: 215579    	Blocks: 424        IO Block: 4096   regular file
Device: 1000feh/1048830d	Inode: 205283981   Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-03-05 16:00:12.000000000
Modify: 2020-03-05 16:00:12.000000000
Change: 2020-06-02 17:24:15.000000000

/ # apk add --no-cache ca-certificates
...
/ # apk del --no-network ca-certificates
...

/ # stat -L /etc/ssl/cert.pem
stat: can't stat '/etc/ssl/cert.pem': No such file or directory
```

I'll have a PR to workaround it shortly. :+1:

**Comment by yosifkit** [comment]
Filed a bug upstream: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11663
