### ISSUE TITLE
haproxy 1.6 with PCRE JIT and lua

### ISSUE THREAD

**Issue by git001** [docker-library/haproxy#12]
Hi.

I have created a docker file which is based on centos:latest and I have added lua 5.3 in the container. ;-)

I have chose centos:latest due to the fact that there the PCRE Lib have the jit enabled.

You can find the repo her https://github.com/git001/haproxy

**Comment by tianon** [comment]
Is this simply an FYI for users who may be interested, or is there a proposed improvement here?

**Comment by tianon** [comment]
(Closing for now, but if there's a specific improvement we should make, I think a new issue with more details would be appropriate; thanks!)

**Comment by jsierles** [comment]
I'm interested to know if we can have official support for Lua. Thanks!
