### ISSUE TITLE
haproxy.conf is not created 

### ISSUE THREAD

**Issue by ypatel26** [docker-library/haproxy#127]
so when I try to run container it fails cmd because it cannot find haproxy.conf file.  Any idea why that file is not getting created?

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/haproxy#how-to-use-this-image
>Since no two users of HAProxy are likely to configure it exactly alike, this image does not come with any default configuration.

>Please refer to upstream's [excellent (and comprehensive) documentation](https://cbonte.github.io/haproxy-dconv/) on the subject of configuring HAProxy for your needs.

>It is also worth checking out the [examples/ directory from upstream.](http://git.haproxy.org/?p=haproxy-1.8.git;a=tree;f=examples)
