### ISSUE TITLE
haproxy baed on Jessie with package

### ISSUE THREAD

**Issue by cjeanneret** [docker-library/haproxy#13]
Hello,

It would be far, far better to create an image based on debian:jessie, and to use the following repository instead of building haproxy:
http://haproxy.debian.net/

This would allow all haproxy versions to run on a up-to-date Jessie without any problem.

I might provide a PR if you're interested.

Cheers,

C.

**Comment by yosifkit** [comment]
We try to follow upstream's recommended method of installation and upstream only releases the source.  It seems we missed this repo in the bumps from wheezy, so we can at least bump the Debian version to `jessie` without any fuss (I just tested it and it seemed to build fine, https://github.com/docker-library/haproxy/pull/14).

**Comment by cjeanneret** [comment]
Hello,

Cool for the bump to Jessie. Small thing tough: you compile haproxy without any LUA support, which limits a lot the capabilities.
Using the haproxy.debian.net repository will provide lua 5.3 and related support in haproxy. As said, this repository is maintained by the official debian haproxy guy, and follows the upstream pretty well.

Plus this would allow to do the following:
```Dockerfile
FROM haproxy
RUN apt-get update && apt-get upgrade -y
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
```

The tiny difference would be haproxy default file location, in /etc/haproxy — the package also provides a default haproxy.cfg so that people might start it faster.

Cheers,

C.

**Comment by klausenbusk** [comment]
I opened a PR #18

**Comment by tianon** [comment]
I think it's probably worthwhile to mirror https://github.com/docker-library/haproxy/pull/18#issuecomment-197500006 here, since I added a bit of additional color there:

> Still the same reservations ... we try to stick to upstream's recommended package source (preferring most strongly packages provided directly by upstream).  This also now has the added effect of causing a further divergence in our Alpine variants, which I wouldn't have as much issue with if the packages were provided, maintained by, or recommended explicitly by upstream as the canonical way to use HAProxy (being a Debian Developer myself, I say this with all due respect to the Debian maintainers, who I'm sure do an awesome job).

Regardless, thanks for the suggestion!
