### ISSUE TITLE
2.4dev8

### ISSUE THREAD

**Issue by wdauchy** [docker-library/haproxy#143]
I don't know exactly the process but https://github.com/docker-library/official-images has not yet been updated with dev8

Thanks

**Comment by wglambert** [comment]
https://github.com/docker-library/haproxy/commit/827001ed9bd67c3b50168a978859c5007576d56a

https://github.com/docker-library/haproxy#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

A PR will be up sometime soon to push the changes

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/9637 :+1:
