### ISSUE TITLE
v2.3.9 quick update

### ISSUE THREAD

**Issue by wdauchy** [docker-library/haproxy#149]
Hello,

We might want to quickly update to v2.3.9 http://git.haproxy.org/?p=haproxy-2.3.git;a=commit;h=53945bf8cde846893bfb9a32e31b40ca9eab4310 there is an annoying bug with sticky tables potentially affecting many people

**Comment by wdauchy** [comment]
cc @tianon

**Comment by tianon** [comment]
Appreciate the heads up!  I've kicked the automation now. :+1:
