### ISSUE TITLE
Can't find bound config file on OSX

### ISSUE THREAD

**Issue by robwold** [docker-library/haproxy#155]
I can see that other people have asked similar questions and it's been user error, so apologies if this turns out to be the same.

Given some attempt to run an container based on the `1.7` image on Mac os I always get the following error:
```
Roberts-MBP:etc Rob$ docker run -it --name my-running-haproxy -v $HAPROXY_CONFIG_DIR:/usr/local/etc/haproxy:ro haproxy:1.7
<7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -db -f /usr/local/etc/haproxy/haproxy.cfg -Ds 
[ALERT] 126/201110 (10) : Cannot open configuration file/directory /usr/local/etc/haproxy/haproxy.cfg : No such file or directory
<5>haproxy-systemd-wrapper: exit, haproxy RC=1
```
However, my folder does contain a config file for haproxy:
```
Roberts-MBP:etc Rob$ ls $HAPROXY_CONFIG_DIR/ | grep haproxy.cfg
haproxy.cfg
```
My colleague seemed to have the same issue on OSX, and we have an instance running successfully on a linux machine.I'm using docker desktop 3.3.1, docker engine 20.10.5.

**Comment by tianon** [comment]
I'm not certain, but I imagine this is probably related to https://docs.docker.com/docker-for-mac/#file-sharing -- is `$HAPROXY_CONFIG_DIR` inside one of the directories that's shared with the Docker VM?

**Comment by robwold** [comment]
No, and moving my config file to /tmp fixes the issue so it's certainly related- thank you!
