### ISSUE TITLE
Failure "cannot bind socket", latest centos 7 does not support net.ipv4.ip_unprivileged_port_start

### ISSUE THREAD

**Issue by jamshid** [docker-library/haproxy#159]
My haproxy image is based on haproxy:2.2 but I recently added `USER haproxy` in preparation for the upgrade to your 2.4 image.

But that breaks on centos7 -- cannot bind to port 80. This is mentioned in https://hub.docker.com/_/haproxy but the sysctl setting you document not seem to work. I'm using latest docker-ce 20.10.6 on centos 7.9.2009 and disabled selinux.

Does `net.ipv4.ip_unprivileged_port_start=0` require a newer kernel?
If so it would be good to mention this on your hub page along with any possible workarounds. 

For now I removed the `USER haproxy` from my Dockerfile and am continuing to base on haproxy:2.2.

```
$ docker logs myhaproxycontainer
....
Using epoll() as the polling mechanism.
[NOTICE] 152/151037 (8) : haproxy version is 2.2.14-a07ac36
[NOTICE] 152/151037 (8) : path to executable is /usr/local/sbin/haproxy
[ALERT] 152/151037 (8) : Starting frontend www-http: cannot bind socket [0.0.0.0:80]
[ALERT] 152/151037 (8) : Starting frontend www-https: cannot bind socket [0.0.0.0:443]

$ uname -a
Linux X 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

$ docker run -ti --sysctl net.ipv4.ip_unprivileged_port_start=0 myhaproxy:2.2
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.ipv4.ip_unprivileged_port_start: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Comment by wglambert** [comment]
Yeah the kernel needs to be at least 4.11 https://github.com/moby/moby/issues/8460#issuecomment-312459310
The haproxy docs should mention that like php's https://github.com/docker-library/docs/tree/master/php#running-as-an-arbitrary-user

**Comment by yosifkit** [comment]
Centos 8 is new enough: https://forums.centos.org/viewtopic.php?f=47&t=77225#p324632
