### ISSUE TITLE
cannot bind socket (Permission denied) [0.0.0.0:80]

### ISSUE THREAD

**Issue by jakevis** [docker-library/haproxy#162]
So when starting with my configuration I get:
[NOTICE]   (1) : haproxy version is 2.4.0-6cbbecf
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (1) : Starting frontend fe_web: cannot bind socket (Permission denied) [0.0.0.0:80]
[ALERT]    (1) : Starting frontend fe_web: cannot bind socket (Permission denied) [0.0.0.0:443]
[ALERT]    (1) : [haproxy.main()] Some protocols failed to start their listeners! Exiting.

This is the same issue seen here: https://github.com/docker-library/haproxy/issues/160

I can resolve this by moving from latest, back to haproxy:2.3.9.
I am guessing something isnt quite right in the docker image?

**Comment by yosifkit** [comment]
The image is fine. We explicitly only added the `USER` for 2.4 and up.  If you need a "privileged" port (less than 1024), then my comment on 160 is the answer: https://github.com/docker-library/haproxy/issues/160#issuecomment-856987103.  If you don't have a new enough kernel then just adding `--user root` to your `docker run` is enough.
