### ISSUE TITLE
haproxy v2.4.1

### ISSUE THREAD

**Issue by wdauchy** [docker-library/haproxy#163]
Hello,

v2.4.1 is out http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=1ce7d49252b1b9c767ab676bd178cccc35929d28
could you please start the bot to update it?

**Comment by TimWolla** [comment]
I also noticed this and messaged the maintainers [in IRC](https://github.com/docker-library/official-images/#contributing-to-the-standard-library) two hours ago.

**Comment by yosifkit** [comment]
The test build is failing so it doesn't commit the update:
>```console
>+ make -C /usr/src/haproxy -j 2 all 'TARGET=linux-musl' 'USE_GETADDRINFO=1' 'USE_LUA=1' 'LUA_INC=/usr/include/lua5.3' 'LUA_LIB=/usr/lib/lua5.3' 'USE_OPENSSL=1' 'USE_PCRE2=1' 'USE_PCRE2_JIT=1' 'USE_PROMEX=1' 'EXTRA_OBJS= 		'
>make: /bin/sh: Operation not permitted
>make: /bin/sh: Operation not permitted
>```

The build is failing for the same reason as all of the Alpine 3.14 based builds are failing: because our builder doesn't have https://github.com/opencontainers/runc/pull/2750.  We're working to update `docker` + `runc` on the builder.

**Comment by tianon** [comment]
Builders are updated and builds are either queued or in progress -- sorry for the delay!

https://github.com/docker-library/haproxy/commit/8cac7162fb3fb4431208d98c2cd9c63d1897421f -> https://github.com/docker-library/official-images/pull/10424
