### ISSUE TITLE
haproxy v2.4.2 is out

### ISSUE THREAD

**Issue by wdauchy** [docker-library/haproxy#164]
see http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=553dee32630347e78cc3a33001c40d26d4245d23
if you could run the bot

Thanks

**Comment by tianon** [comment]
The bot runs automatically every 6 hours: https://github.com/docker-library/haproxy/commit/973f43b2d1c5c0d57274002e216761c0baedf6c0 :smile: :+1:

(and https://github.com/docker-library/official-images/pull/10494 is open now)

**Comment by wdauchy** [comment]
thanks!
