### ISSUE TITLE
Opentracing integration

### ISSUE THREAD

**Issue by Drevoed** [docker-library/haproxy#165]
Maybe it would be a good idea to use a 
```
USE_OT=1
```
`make` flag to allow opentracing integration out of the box?

https://www.haproxy.com/blog/announcing-haproxy-2-4/

**Comment by tianon** [comment]
Sorry for the delay :weary:

> To enable it, first you must install the [opentracing-c-wrapper](https://github.com/haproxytech/opentracing-c-wrapper).

This is my first hesitation, and https://github.com/haproxytech/haproxy-docker-alpine/issues/5#issuecomment-1091170250 is my second :sweat_smile:

**Comment by tianon** [comment]
I'm going to close this as it's not something we plan to implement (given the above), but happy to reconsider if there's an official recommendation from HAProxy upstream that it should be enabled by default for all users in the future. :+1:
