### ISSUE TITLE
HAProxy container on VM timing out on public address randomly after creation?

### ISSUE THREAD

**Issue by grantyoung** [docker-library/haproxy#173]
Hey. Bit of a weird one this.

Basically I'm setting up a HAProxy docker container on a VM (Ubuntu) in Azure. The VM has a public address and the container is configured to listen on port 80 like normal.

It works some of the time. When it does everything is grand and the container works as expected.

However when I run my automation, which deletes and recreates the docker container by default to pick up the latest image, it always passes with the container running but I then get a constantly loading connection whenever I try to load up the public address. This seems to happen around half of the time. When it does happen it appears to resolve itself after a notable period of time, maybe something like 30 mins?

Nothing else has changed in this scenario. Firewall is correct, the port itself is open but it just times out. Restarting the docker container solves the issue most of the time but sometimes it just happens again.

This doesn't happen when I try the same thing on GCP so I assume it's something more Azure related? I've tried both bridge and host networking and several other common things but nothing seems to help. Any help would be awesome thanks!

**Comment by wglambert** [comment]
It sounds like it's Azure related then if it works fine on GCP? I'd imagine if it was an issue with the image then it would exhibit the issue on any platform not just one in particular. Is there anything in the logs showing an error?

**Comment by grantyoung** [comment]
It appears this was due to needing `net.ipv4.ip_unprivileged_port_start` configured with the HAProxy container.

Since adding that I've not seen the issue. Apologies for the noise!
