### ISSUE TITLE
How to obtain the ARM version of haproxy? 

### ISSUE THREAD

**Issue by fantastic2085** [docker-library/haproxy#187]
**1. https://hub.docker.com/_/haproxy?tab=tags Does the image obtained from this link support ARM?**
**2.https://hub.docker.com/_/haproxy?tab=tags Will the docker image downloaded by this link automatically adapt?**

**Comment by yosifkit** [comment]
Yes, it supports `arm64v8`, `arm32v5` and `arm32v7` as seen in the manifest for `latest`. The Alpine-based versions have a slightly different set of supported architectures.

![image](https://user-images.githubusercontent.com/896423/173611817-23ab0fd2-83fb-4121-af3e-19df2fb52bbf.png)

Docker should pull the "best" host CPU matching architecture on `docker pull` (this can be semi-controlled with the `--platform` flag). If you need to exactly pull a specific architecture, they are also pushed to architecture specific namespaces on Docker Hub, like https://hub.docker.com/r/arm64v8/haproxy/. Once you pull an image, it is only for a specific architecture; you need to `docker pull` again to get a different architecture.
