### ISSUE TITLE
If you have a new enough kernel (`4.11`), then adding `--sysctl net.ipv4.ip_unprivileged_port_start=0` to the `docker run` should allow it to use "privileged" ports (https://github.com/moby/moby/issues/8460).

### ISSUE THREAD

**Issue by Vahid22h** [docker-library/haproxy#206]
If you have a new enough kernel (`4.11`), then adding `--sysctl net.ipv4.ip_unprivileged_port_start=0` to the `docker run` should allow it to use "privileged" ports (https://github.com/moby/moby/issues/8460).

If you have both a new enough kernel and new enough `docker` (`20.10.x`, https://github.com/moby/moby/commit/dae652e2e5e47d99c8febd5bc81df0a3269beb74), then it can just work: https://github.com/moby/moby/pull/41030.

_Originally posted by @yosifkit in https://github.com/docker-library/haproxy/issues/160#issuecomment-856987103_

**Comment by yosifkit** [comment]
This issue looks opened in error and seems indistinguishable from spam without a report of what needs changing/fixing.
