### ISSUE TITLE
Cannot find logging 

### ISSUE THREAD

**Issue by sw360cab** [docker-library/haproxy#23]
It is possible to get logging of HAProxy from the container?

**Comment by erezny** [comment]
HAProxy likes to log with syslog and doesn't log to the docker logs. You can configure it to log to a syslog server and work with your logs from there.

http://cbonte.github.io/haproxy-dconv/configuration-1.6.html?#log global

**Comment by yosifkit** [comment]
Closing old issue in favor of discussion on https://github.com/docker-library/haproxy/pull/39.
