### ISSUE TITLE
Reloading Haproxy creating a New haproxy process and for next time reload it update the 2nd haproxy process So overall 2 haproxy process are there

### ISSUE THREAD

**Issue by basivireddy** [docker-library/haproxy#25]
Reloading Haproxy creating a New haproxy process and for next time reload it update the 2nd haproxy process So overall 2 haproxy process are there

**Comment by tianon** [comment]
I'm not sure I'm following what the bug here is -- two processes is the expected behavior.  Is this causing some more specific issue?

**Comment by basivireddy** [comment]
yes.It's has two process so the traffic goes to two process.Let initial process has {apache1,apache2} and then added {apache3} so 2nd process has {apache1,apache2,apache3}.

The traffic flow like 1st process and next 2nd process.
Traffic: {apache1,apache2} , {apache1,apache2,apache3},{apache1,apache2} , {apache1,apache2,apache3}

It's not regular behaviour but expected behaviour like as {apache1,apache2,apache3}
,{apache1,apache2,apache3}


So We created haproxy with supervisord as init process,Now it's working fine.
