### ISSUE TITLE
Outdated URL in the 1.6 Dockerfile comment

### ISSUE THREAD

**Issue by jusle** [docker-library/haproxy#26]
Line 9 should be
`# see http://sources.debian.net/src/haproxy/1.6.4-3/debian/rules/ for some helpful navigation of the possible "make" arguments` instead of `# see http://sources.debian.net/src/haproxy/1.5.8-1/debian/rules/ for some helpful navigation of the possible "make" arguments`.

**Comment by tianon** [comment]
This was mostly fixed via https://github.com/docker-library/haproxy/pull/38, and finished via https://github.com/docker-library/haproxy/pull/63. :+1:

(Using "https://sources.debian.net/src/haproxy/jessie/debian/rules/" instead, which will auto-resolve to the latest release in the `jessie` distribution.)
