### ISSUE TITLE
haproxy.cfg not found when deploying to heroku

### ISSUE THREAD

**Issue by admosity** [docker-library/haproxy#29]
I have setup a working example and a bad example (working example on branch heroku-good):

https://github.com/admosity/docker-heroku-haproxy-fail

I am unable to get this to run correctly using the default Dockerfile configuration:

```
FROM haproxy:1.6-alpine
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
```

After deploying to heroku I get:

```
2016-09-08T21:32:28.522203+00:00 app[web.1]: /docker-entrypoint.sh: exec: line 15: haproxy -f /usr/local/etc/haproxy/haproxy.cfg: not found
```

In the working example I copied the dockerfile specified here and commented out the entry point and put the haproxy.cfg copy on the line where that was. I'm pretty new to docker, so not sure if I am doing something wrong.

Here it is working with the good example (I'm proxying example.com):
https://evening-thicket-58251.herokuapp.com/

![image](https://cloud.githubusercontent.com/assets/4655972/18368704/55cae228-75ef-11e6-8a29-859666dadfcc.png)

**Comment by yosifkit** [comment]
It looks like Heroku is processing Dockerfiles in a non-compliant way.

```console
$ # The way docker interprets the image entrypoint and cmd:
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]

$ # becomes
$ # run this executable in the image: "/docker-entrypoint.sh"
$ # with these arguments: "haproxy" "-f" "/usr/local/etc/haproxy/haproxy.cfg"
$ # ie eqivalent to bash: 
$ /docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg

$ # whereas it looks like heroku is doing this:
$ # run this executable in the image: "/docker-entrypoint.sh"
$ # with this argument: "haproxy -f /usr/local/etc/haproxy/haproxy.cfg"
$ # ie eqivalent to bash: 
$ /docker-entrypoint.sh 'haproxy -f /usr/local/etc/haproxy/haproxy.cfg'
```

You should be able to do the following in your Dockerfile to override the entrypoint:
```Dockerfile
FROM haproxy:1.6-alpine
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

ENTRYPOINT []
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
# though you could also do one of these, since heroku interprets it this way anyway:
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["haproxy -f /usr/local/etc/haproxy/haproxy.cfg"]
ENTRYPOINT []
CMD haproxy -f /usr/local/etc/haproxy/haproxy.cfg
```

**Comment by admosity** [comment]
Awesome and thanks for the quick reply!

Here's my results from trying the solutions you provided:

Works:
```
ENTRYPOINT []
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
```

```
ENTRYPOINT []
CMD haproxy -f /usr/local/etc/haproxy/haproxy.cfg
```

Doesn't work:
```
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["haproxy -f /usr/local/etc/haproxy/haproxy.cfg"]
```
![image](https://cloud.githubusercontent.com/assets/4655972/18389137/710a1134-7672-11e6-8ba0-063b66e7299e.png)

**Comment by yosifkit** [comment]
That is a bit unexpected. :confused:   Well at least it is working on some and hopefully this conversation can help more people in the future when they get "command not found" when deploying to heroku using docker images.

**Comment by admosity** [comment]
Cool. I opened a ticket on heroku as well referencing this issue. We'll see how it goes.

**Comment by admosity** [comment]
This is the response I got:

> Thanks for reporting this issue, we indeed process ENTRYPOINT and CMD slightly different than docker due to the nature of Heroku environment, we will prefix your CMD with /bin/sh -l -c when no ENTRYPOINT is specified to will make sure your heroku config vars (including those you defined your Dockerfile during the build of your image) are loaded (-l) and available for your CMD execution, we are aware of this difference (I believe this is also noted in the public documentation, if not I will make sure to update) but we are also working on a better support for ENTRYPOINT + CMD combinations, for now your workaround is correct and should also be supported when we ship better support for entrypoint and cmd.

**Comment by tianon** [comment]
Closing given that this is a downstream issue (not something we can fix in the image itself).
