### ISSUE TITLE
Haproxy does not support ALPN with Openssl 1.0.1

### ISSUE THREAD

**Issue by rbjorklin** [docker-library/haproxy#32]
We're trying to use this docker image with Jetty which requires ALPN to support HTTP2. This means we need ALPN support currently not provided by the image. See the note here: http://www.eclipse.org/jetty/documentation/current/http2-configuring-haproxy.html

Could this image be updated to include openssl 1.0.2 or greater?

**Comment by yosifkit** [comment]
We are currently limited to the versions of openssl in debain:jessie and alpine:3.4.  It looks like we can get [`libssl-dev` at `1.02j`](https://packages.debian.org/jessie-backports/libssl-dev) if we switch to `debian:jessie-backports`.  The version in [alpine 3.4](https://pkgs.alpinelinux.org/package/v3.4/main/x86/openssl-dev) looks to be new enough (`1.0.2j-r0`).

**Comment by rbjorklin** [comment]
We ended up going another route so I'm closing this issue. I also realized I provided to little details, what we actually needed was for haproxy to be built with openssl >= 1.0.2. This can be verified with `haproxy -vv | grep -i openssl`. I checked the `debian:jessie-backports` images and that haproxy was built with a too old version of openssl.

**Comment by yosifkit** [comment]
The haproxy from debian apt repos is not the one we use. We compile from source to be as close to upstream as possible.  The only thing we gain from backports is a newer openssl.  The alpine based images already have openssl 1.0.2:

```console
$ docker run -i --rm haproxy:1.6-alpine sh -c 'haproxy -vv | grep -i openssl'
  OPTIONS = USE_ZLIB=1 USE_OPENSSL=1 USE_PCRE=1
Built with OpenSSL version : OpenSSL 1.0.2j  26 Sep 2016
Running on OpenSSL version : OpenSSL 1.0.2j  26 Sep 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports prefer-server-ciphers : yes
```

**Comment by sylvainmouquet** [comment]
How to get openssl 1.0.2 to haproxy docker 1.7 (not alpine version) ?
