### ISSUE TITLE
haproxy returns 5xx if a proxied url is not accessible during startup

### ISSUE THREAD

**Issue by fabiand** [docker-library/haproxy#37]
If you start a haproxy and a specific path is not reachable on the first request, then haproxy will never retry that path and will return 5xx on subsequent requests.

See also https://github.com/kubevirt/kubevirt/issues/27

**Comment by tianon** [comment]
Isn't this an issue with the HAProxy configuration (or with HAProxy upstream), and not something specific to this image?  Not sure what we could do to fix this. :confused:
