### ISSUE TITLE
support LUA_PATH

### ISSUE THREAD

**Issue by bradrobertson** [docker-library/haproxy#42]
Right now haproxy looks for lua files in the same directory the script is run from. It'd be nice to also support a LUA_PATH env var that we can place script into.

1. Would adding this env var make sense?
2. What dir would you want used if I put together a PR ?

**Comment by tianon** [comment]
I think you're going to need to elaborate a bit on what this environment variable would do -- isn't the Lua support controlled by the HAProxy configuration file? (which we explicitly don't provide)

**Comment by tianon** [comment]
Closing since I don't understand fully what the goal of this new environment variable would be (or what the implementation details would look like).  It _seems_ like something that should probably be taken up with HAproxy upstream instead though. :+1:
