### ISSUE TITLE
[1.8] SSL/TLS Mode Async

### ISSUE THREAD

**Issue by lpfeup** [docker-library/haproxy#55]
I have tried to make HAProxy work with async SSL/TLS as explained [here](https://www.haproxy.com/blog/whats-new-haproxy-1-8/), by adding :
```
global
  ssl-engine rdrand 
  ssl-mode-async
```

but I get 

> [ALERT] 331/144013 (1) : ssl-engine rdrand: failed to get structural reference

Am I missing something here?

Thanks in advance

**Comment by qedrakmar** [comment]
Can you provide the rest of your haproxy.cfg so we can try to reproduce this?

**Comment by weikinhuang** [comment]
Opens v1.1.x is needed to support this according to the async ssl section https://www.haproxy.com/blog/whats-new-haproxy-1-8/

**Comment by yosifkit** [comment]
As far as I can tell we have everything necessary (openssl `1.1.0f`: [libssl1.1](https://packages.debian.org/stretch/libssl1.1) and [libssl-dev](https://packages.debian.org/stretch/libssl-dev)) and build with `USE_OPENSSL=1`.  I don't see any options in the [Makefile](http://git.haproxy.org/?p=haproxy-1.8.git;a=blob;f=Makefile;h=26b55db9da392160110f99a2364aea03ba5bcd70;hb=HEAD) that is specific to enable async SSL/TLS.

**Comment by weikinhuang** [comment]
I don't believe the Alpine variant is built against openssl 1.1.

**Comment by yosifkit** [comment]
@weikinhuang That is correct, Alpine only has [`1.0.2m`](https://pkgs.alpinelinux.org/package/v3.6/main/x86_64/libssl1.0) of openssl available. I would assume that is because they have been moving all of their packages to use libressl.

@lpfeup, You also need to be running on hardware that supports `rdrand`. On my machine (Intel i7 7700k) I can see the `rdrand` engine in openssl engine list, but my coworker's machine on an AMD processor does not list it.

```console
$ docker run -it --rm haproxy:1.8 bash
root@694332c9a62b:/# apt-get update
...
root@694332c9a62b:/# apt-get install openssl
...
The following NEW packages will be installed:
  openssl
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 725 kB of archives.
After this operation, 1273 kB of additional disk space will be used.
Get:1 http://security.debian.org stretch/updates/main amd64 openssl amd64 1.1.0f-3+deb9u1 [725 kB]
Fetched 725 kB in 1s (626 kB/s)  
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package openssl.
(Reading database ... 6334 files and directories currently installed.)
Preparing to unpack .../openssl_1.1.0f-3+deb9u1_amd64.deb ...
Unpacking openssl (1.1.0f-3+deb9u1) ...
Setting up openssl (1.1.0f-3+deb9u1) ...
root@694332c9a62b:/# openssl engine
(rdrand) Intel RDRAND engine
(dynamic) Dynamic engine loading support
root@694332c9a62b:/# 
```

**Comment by lpfeup** [comment]
@yosifkit In my case it was lack of hardware support (machine does not list `rdrand`).

**Comment by EmericBr** [comment]
Just for note: ssl-mode-async is useless on engine rdrand, since this engine doesn't use a device and was not blocking. ssl-mode-async was designed to work using intel quick assist engine.
