### ISSUE TITLE
Use lua from system package

### ISSUE THREAD

**Issue by lorddaedra** [docker-library/haproxy#61]
Here 
https://pkgs.alpinelinux.org/package/v3.7/main/x86_64/haproxy
is haproxy package from Alpine, it's outdated but for us is interesting to see on depends packages.

It depends on libressl (for security reasons, less bugs than in openssl) and lua5.3-libs.

I'm already wrote about libressl in another issue (#60) and here I suggest to use system lua libs package instead of manually installed... If I understand correctly reason was with outdated package version, but now it's is available from Alpine package system and it should be preferred way in my opinion if we have not any other reasons...

**Comment by lorddaedra** [comment]
so build dep is ```lua5.3-dev``` (can be removed after installing haproxy)
https://pkgs.alpinelinux.org/package/v3.7/main/x86_64/lua5.3-dev , 

run dep is ```lua5.3```
https://pkgs.alpinelinux.org/package/v3.7/main/x86_64/lua5.3 (include lua5.3-libs) or just ```lua5.3-libs```
 https://pkgs.alpinelinux.org/package/v3.7/main/x86_64/lua5.3-libs

**Comment by yosifkit** [comment]
I've finally made a PR in #63.  Thanks for the info here.
