### ISSUE TITLE
TLS 1.3 and OpenSSL 1.1.1

### ISSUE THREAD

**Issue by Santinell** [docker-library/haproxy#74]
11 September 2018 was released final version of OpenSSL 1.1.1 (LTS)
How about use it in docker image for supporting TLS 1.3 and 0RTT ?

**Comment by yosifkit** [comment]
Alpine based images are built on Alpine 3.8, which only has OpenSSL 1.0.2o ([pkgs.alpinelinux](https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.8)).  The Debian based images are built on Debian Stretch, which only has OpenSSL version 1.1.0f ([openssl packages](https://packages.debian.org/source/stretch/openssl))

**Comment by Santinell** [comment]
I think it's not a big deal build OpenSSL 1.1.1 from sources...
We are talking about docker image where such things as building from source is common and for users it's not take any time

**Comment by tianon** [comment]
Is there an official recommendation from the HAproxy project to use this
newer version of OpenSSL?  Barring that I'm personally opposed to the added
maintenance burden of building it from source.

**Comment by Santinell** [comment]
I think it's a kind of recommendation:
https://www.haproxy.com/blog/tls-1-3-0-rtt-haproxy/

HAProxy almost a year support TLS 1.3 and 0-RTT, which can't be used because of old version of OpenSSL.
By the way building is automatic, you don't need to wait it near the monitor all the time.

**Comment by TimWolla** [comment]
There's still some administrative issues for TLS 1.3: https://www.mail-archive.com/haproxy@formilux.org/msg31209.html

I believe we should wait for haproxy 1.9 at least, before providing images with TLS 1.3 support.

**Comment by lukastribus** [comment]
Wait a few days for 1.9.1, it fixes the DNS issue that affects a lot of docker setups.

**Comment by paradizelost** [comment]
I've submitted a pull request for a dockerfile that enables tls 1.3

**Comment by J0WI** [comment]
This is fixed in #82
