### ISSUE TITLE
"unspecified DNS error" with resolvers v1.8.15 in master-worker mode

### ISSUE THREAD

**Issue by flavioaiello** [docker-library/haproxy#78]
As soon I updated to the recently available v1.8.15, all backends resolving dynamic with dns go to DOWN state due to a `unspecified DNS error`. Switching back to v1.8.14 brings everything back to normal.

**Comment by lukastribus** [comment]
Issue is already [fixed in the dev branch](https://github.com/haproxy/haproxy/commit/8d4e7dc880d2094658fead50dedd9c22c95c556a), and there is [the intention to release 1.8.16 shortly](https://www.mail-archive.com/haproxy@formilux.org/msg32172.html).

**Comment by lukastribus** [comment]
Released: [[ANNOUNCE] haproxy-1.8.16](https://www.mail-archive.com/haproxy@formilux.org/msg32183.html)

**Comment by flavioaiello** [comment]
lgtm but `haproxy:1.8.16-alpine` is not yet available

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/5221 -- updated tags should be available soon. :+1:
