### ISSUE TITLE
Error when using with redis cluster

### ISSUE THREAD

**Issue by jchanam** [docker-library/haproxy#8]
Hi!

We are using your container, and we are getting some problems with redis cluster.

We have based our configuration file on this [HAProxy blog entry](http://blog.haproxy.com/2014/01/02/haproxy-advanced-redis-health-check/).

What we've seen is that even if it assumes two of the nodes are down on the stats page, it stills redirect the request to two instances (to the master and one of the slaves), so, it's not working properly. We think this is problem of using it inside a docker, because if using outside, it does not happen.

Our cfg is the following:

```
global
	log 127.0.0.1 local0
	log 127.0.0.1 local1 notice
	stats timeout 30s
	maxconn 131070
	ulimit-n 262500
	nbproc 1
	user root
	group root

listen stats :1936
    mode http
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /
    stats auth admin:admin

listen redis :6379
    mode tcp
    option tcplog
    option tcp-check
    tcp-check send PING\r\n
    tcp-check expect string +PONG
    tcp-check send info\ replication\r\n
    tcp-check expect string role:master
    tcp-check send QUIT\r\n
    tcp-check expect string +OK
    server redis_01 X.X.X.1:6379 maxconn 1024 check inter 1s
    server redis_02 X.X.X.2:6379 maxconn 1024 check inter 1s
    server redis_03 X.X.X.3:6379 maxconn 1024 check inter 1s
```

Could anyone tell us if this has been seen before? Is there any problem on our config file?

Thanks in advance!

**Comment by jchanam** [comment]
In order to add you info, what we get through logs is the following:

```
[WARNING] 214/091626 (1) : Server redis/redis_01 is DOWN, reason: Layer7 timeout, info: " at step 4 of tcp-check (expect string 'role:master')", check duration: 1001ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 214/091626 (1) : Server redis/redis_02 is DOWN, reason: Layer7 timeout, info: " at step 4 of tcp-check (expect string 'role:master')", check duration: 1001ms. 1 active and 0 backup servers left. 1 sessions active, 0 requeued, 0 remaining in queue.
```

Thanks!

**Comment by ebuildy** [comment]
Can you explain a bit more your infrastructure? Such as number of Docker hosts, private/public networks ....

**Comment by jchanam** [comment]
All the dockers are running inside the same VM's. Docker is only used on the VM_X (drawn below). The PHP-FPM connects to the HAProxy  in order to connect to the redis master.

We've got:
```
VM_X
+---------------------------------------------+    VM_Y[1|2|3]
| +---------+    +-----------+    +---------+ |    +---------------+
| | Varnish | -> | Nginx+PHP | -> | HAProxy | | -> | Redis Cluster |
| +---------+    +-----------+    +---------+ |    +---------------+
+---------------------------------------------+
```

What we've found out, is that the dockers maintain the connections open, and, because of there are "different" machines, does not find out the HAProxy has been restarted.

Is there any option to make the dockers restart on cascade?
Is there any way to make the dockers know that other one has been restarted?

Thanks!

**Comment by yosifkit** [comment]
So the HAProxy container is restarted, getting a new IP, and the PHP container has a `--link my-haproxy:custom-haproxy` to it?  Currently there is not a simple way to cascade restarts, but, as long as it is the same container (ie just a `docker stop` and `start`), the PHP container would get an updated entry in `/etc/hosts` with the new IP. So now the PHP container can hit `custom-haproxy` or whatever the link name is.

I am not sure I am even debugging in the right area, but maybe this helps :confused:.

**Comment by jchanam** [comment]
Hi!

Yes, I've got the containers linked as you've said.

What I'm trying to do is a script that, via docker api, checks the updated time and, based on setted dependencies, restart the dockers.

I don't know if there's an easier way of doing this.

Apart from this, what is strange, is that when the haproxy is restarted, he php can get to redis, but other than the master node. I haven't been able to found out why by now...

Thank you for all your efforts!

**Comment by freiit** [comment]
with docker >=1.9 there is an easier way. Put all containers with 'docker network ...' in a local network, too, so they can find each other always with their names. If you replace a container, just give it the same name and you don't need to replace cascading containers.

**Comment by tianon** [comment]
I agree -- I think the new Docker Networks feature should help mitigate this particular issue.  Regardless, this appears to be an issue specific to Docker's routing, not something inherent to the image.  If that's not the case, I think a new issue with more details explaining what the image is doing wrong and hopefully clues for how we can fix it would be appreciated! :+1:
