### ISSUE TITLE
Cannot open configuration file/directory /usr/local/etc/haproxy/haproxy.cfg : No such file or directory

### ISSUE THREAD

**Issue by JamesLoyd** [docker-library/haproxy#86]
I am trying to run the HaProxy image. I have the following dockerfile:
```
FROM haproxy:1.7
COPY haproxy.cfg /user/local/etc/haproxy/haproxy.cfg
```

But I consistently get this when I run it:
![image](https://user-images.githubusercontent.com/1821671/56594839-879cca00-65bb-11e9-933f-b75f3bcf6f93.png)

I have also tried using just `from haproxy`.

**Comment by wglambert** [comment]
You want `/usr/` instead of `/user/`

**Comment by JamesLoyd** [comment]
That did it!. I looked at that for a long time. Thank you :)
