### ISSUE TITLE
Container fails to startup unless adding the debug flag

### ISSUE THREAD

**Issue by bryceray1121** [docker-library/haproxy#9]
I've encountered a strange issue, and i'm not sure of the root cause.  A disclaimer that I'm relatively new to both docker and haproxy, so it is very likely user error.

By default I've got haproxy set to run without the debug flag, if I run debug start it immediately fails with no information in docker logs.  If I add the debug option to the global section it starts up and runs perfectly.  I've tested multiple times adding and removing the flag.

```
/usr/bin/docker run -d --name haproxy -p 80:80 -v /opt/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro haproxy:1.5.14
```

```
global
  maxconn 4096
  daemon
  node lb1
  spread-checks 5

defaults
  log     global
  mode    http
  option  httplog
  option  dontlognull
  retries 3
  option redispatch
  maxconn 2000
  timeout connect      5000
  timeout client      50000
  timeout server      50000

frontend web
  bind *:80
  mode http
  monitor-uri /haproxy?monitor

  use_backend service if { path_beg /service }
  default_backend service

backend service
  mode http
  option httpclose
  option forwardfor

  balance roundrobin

  cookie SRVID insert indirect nocache
  option nolinger

  server app1_1 microserviceurl:80 cookie app1_1 check inter 10s rise 2 fall 2
```

Any suggestions on why this might be happening?

**Comment by yosifkit** [comment]
FYI, for those in the future: it should be the `daemon` flag that is causing the issue :wink:.  Once removed it should work fine.

**Comment by datacarl** [comment]
So it's not possible to run it with `-d`? Is the suggested approach not to run it as a daemon? It does make it a lot less useful, no? What's required to make it run as a daemon (`million12/haproxy` does it already)?

**Comment by datacarl** [comment]
Ok so this is a workaround

`docker run -d --name my-running-haproxy -v /path/to/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro haproxy:1.5 haproxy -db -f /usr/local/etc/haproxy/haproxy.cfg`

**Comment by yosifkit** [comment]
@datacarl, yes you can run the container in the background.  The problem is running the process in daemon mode since it forks and the parent process exits, thus pid 1 exits and the container exits.
