### ISSUE TITLE
needs rebuild with openssl 1.1.1+

### ISSUE THREAD

**Issue by sandys** [docker-library/haproxy#96]
ssl-default-bind-ciphersuites - This setting is only available when support for OpenSSL was built in and OpenSSL 1.1.1 or later was used to build HAProxy. 

this is now being used by all generators including mozilla (e.g. https://ssl-config.mozilla.org/#server=haproxy&server-version=1.9.8&config=intermediate) and this does not work on the docker images.

**Comment by wglambert** [comment]
Currently the image is based off Debian Stretch, whose Openssl from the stretch-stable repo is at version `1.1.0k-1~deb9u1`
https://packages.debian.org/stretch/openssl

Buster uses `1.1.1c-1` and is releasing soon, in the meantime you could try using Openssl from Buster's repo using https://github.com/docker-library/golang/issues/284#issuecomment-502773850 as a reference

**Comment by sandys** [comment]
This is even if I use the alpine image.
Can that not be fixed with the Appropriate version?

**Comment by wglambert** [comment]
The Alpine repos all use version 1.1.1 https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.10

**Comment by tobiaskohlbau** [comment]
I noticed a side effect of updating to openssl 1.1.1+. It looks like the default setting of `Requested Signature Algorithms` changed. Is it possible to change this values within HAProxy or the container? I'm not sure if it is the result of the new openssl version or the update to debian buster (maybe different openssl config on buster?).
